import { defineConfig } from "vitest/config";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      // Generated by vite-plugin-pwa at build time, so it does not exist when
      // vitest resolves imports — without this, `UpdatePrompt.tsx` and anything
      // that renders it cannot be imported by a test at all. See the stub.
      "virtual:pwa-register": new URL("./src/test/pwa-register-stub.ts", import.meta.url).pathname,
    },
  },
  test: {
    environment: "jsdom",
    // `scripts/` holds the container-startup helpers (they render dist/serve.json
    // from runtime env), which are plain ESM rather than app source.
    include: ["src/**/*.test.{ts,tsx}", "scripts/**/*.test.mjs"],
    setupFiles: ["src/test/setup.ts"],
    clearMocks: true,
    restoreMocks: true,
  },
});
