/**
 * Stands in for `virtual:pwa-register` under vitest.
 *
 * That module is generated by vite-plugin-pwa at build time and does not exist
 * when vitest resolves imports, so anything importing it — `UpdatePrompt.tsx`,
 * which is the whole of the app's service-worker registration — could not be
 * loaded in a test at all. `vitest.config.ts` aliases the specifier here.
 *
 * A stub rather than `vi.mock` in each test file: the alias has to exist for the
 * import to resolve in the first place, and once it does, the stub may as well
 * be the double. It records what the component passed so a test can drive the
 * lifecycle callbacks by hand — which is the only way to reach them, since
 * nothing here registers a real worker.
 */

export type RegisterSWOptions = {
  immediate?: boolean;
  onNeedRefresh?: () => void;
  onOfflineReady?: () => void;
  onRegisteredSW?: (swScriptUrl: string, registration?: ServiceWorkerRegistration) => void;
  onRegisterError?: (error: unknown) => void;
};

let lastOptions: RegisterSWOptions | null = null;

export function registerSW(options: RegisterSWOptions = {}): (reloadPage?: boolean) => Promise<void> {
  lastOptions = options;
  return async () => {};
}

/** What the component under test handed `registerSW`, or null if it never did. */
export const lastRegisterSWOptions = (): RegisterSWOptions | null => lastOptions;

export const resetRegisterSWStub = (): void => {
  lastOptions = null;
};
